### ISSUE TITLE
Floating/Cut off Spelunkery geode generation

### ISSUE THREAD

**Issue by MoonsMess** [TelepathicGrunt/TACT#10]
Nephrite geodes from Spelunkery generate floating and cut off in primordial caves. Not sure if any other caves share this issues.

I'm assuming that adding the cave tag to the biomes in alex's caves may have caused this, and I'm not sure if there is a fix, but I just wanted to let you know.

![2024-02-22_17 32 52](https://github.com/TelepathicGrunt/TACT/assets/82176772/8d4e2a33-123a-4938-bdc3-703ef0c43b3c)
![2024-02-22_17 33 48](https://github.com/TelepathicGrunt/TACT/assets/82176772/492f79b0-3e58-41ac-94f0-a3279b40f55a)

**Comment by TelepathicGrunt** [comment]
No, they add their geode to all overworld biomes. Has nothing to do with is_cave actually. 
https://github.com/AstralOrdana/Spelunkery/blob/551b6b6c5d6a64ceeb55ebc494960280d4f27fe9/forge/src/main/resources/data/spelunkery/forge/biome_modifier/overworld_modifier.json#L7

You should make issue report to Spelunkery to ask them to try and keep their geode in the center generating chunks. If they make their geode cross chunk boundaries, it can spawn in a way where part of it goes into the already cave carved chunk because alex's caves generates the caves as a feature.

Or they can make their own block tag for `"cannot_replace": "#minecraft:features_cannot_replace",` and add air/cave air to that so the geode will not replace existing air blocks.

You can also make a datapack that uses the `Remove Features` option to remove Spelunkery's geode from all biomes you don't want it in. The datapack should load and override Spelunkery
https://forge.gemwire.uk/wiki/Biome_Modifiers

**Comment by TelepathicGrunt** [comment]
If you make an issue report to Spelunkery to let them know of this issue, link this issue report so they can read above what I said and can reach out to me if they are having issues

**Comment by TelepathicGrunt** [comment]
I can try making an internal datapack to remove their geode out of the biome but ideally, Spelunkery would make their feature safer so it doesn't mess up other mod's stuff as well

Edit, Spelunkery's geodes should also be spawning in mid-air chopped up in any underground structure with large open space too. Would also impact repurposed structure's underground bastion. Guess I'll need to mixin and stop geode spawning in my structures too...

**Comment by TelepathicGrunt** [comment]
Made issue report to Spelunkery here:
https://github.com/AstralOrdana/Spelunkery/issues/190

If they don't have a fix in place soon, I'll release a TACT update where it has an internal datapack to yeet their features out of Alex's Caves biomes.
