### ISSUE TITLE
Please 1.19.2 Forge <3

### ISSUE THREAD

**Issue by NeoFolia** [TelepathicGrunt/TACT#13]
Please 1.19.2 Forge <3

**Comment by TelepathicGrunt** [comment]
I’m curious. @kitovoi111 how do you envision TACT working in 1.19.2 when Alex’s Caves doesn’t exist in 1.19.2 Minecraft? TACT is just extra adjustments and configs for Alex’s Caves

**Comment by NeoFolia** [comment]
One second

**Comment by kitovoi111** [comment]
https://drive.google.com/file/d/1QGyH7nGClLlRM-JFvA7LLBuxqFoUSAi8/view?usp=sharing (Alex's Caves 1.19.2)
https://drive.google.com/file/d/1A-O4Jjemi_68z510pSH_bofpcbM7K0af/view?usp=sharing (Lib)

**Comment by NeoFolia** [comment]
I would like to see a port of your mod to 1.19.2

**Comment by TelepathicGrunt** [comment]
Yeah I do not trust those links.

Alex's Caves, as per CurseForge site, is not on 1.19.2 
https://www.curseforge.com/minecraft/mc-mods/alexs-caves/files/all?page=1&pageSize=20

If 1.19.2 is posted on the CF page, maybe I'll backport but generally, I do not like backporting ever and have been trying to stop in order to save time
