### ISSUE TITLE
[Feature request] Config option to modify Dreadbow's arrow amount?

### ISSUE THREAD

**Issue by NeuTraLZero** [TelepathicGrunt/TACT#6]
Both for the default dark arrows and when using any other arrows would be awesome

**Comment by TelepathicGrunt** [comment]
You talking about the arrows raining down from sky thing? Just curious though, why do you want to limit the amount? When an entity gets hurt, there's a brief like invincibility frame-like thing. So increasing or decreasing the arrow rain amount won't raise or lower the amount of damage the entity takes because all the arrows hits nearly at same time afaik. https://minecraft.wiki/w/Damage#Immunity

So I just want to know a bit more what your use case is for raising/lowering the amount of arrows

**Comment by TelepathicGrunt** [comment]
added now
